---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-ins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-ins
  template:
    metadata:
      labels:
        app: dep-ins
    spec:
      containers:
        - name: con-ins
          image: ganu1710/projinsurnace:1.0
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            
---
apiVersion: v1
kind: Service
metadata:
  name: dep-ins
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: dep-ins
